ap_personnages_items:
    path:    /{page}
    defaults: { _controller: APPersonnagesBundle:Affiche:Items }

ap_personnages_details:
    path:    /details/{id}
    defaults: { _controller: APPersonnagesBundle:Details:Details }
