ap_personnages_items:
    path:    /
    defaults: { _controller: APPersonnagesBundle:Affiche:Items }

ap_personnages_details:
    path:    /{id}
    defaults: { _controller: APPersonnagesBundle:Details:Details }
