ap_personnages_accueil:
    path:     /
    defaults: { _controller: APPersonnagesBundle:Affiche:Accueil }

ap_personnages_items:
    path:    /liste super-héros
    defaults: { _controller: APPersonnagesBundle:Affiche:Items }
