ap_personnages_accueil:
    path:    /
    defaults: { _controller: APPersonnagesBundle:Accueil:Accueil }
ap_personnages_items:
    path:    /personnages/{page}
    defaults: { _controller: APPersonnagesBundle:Affiche:Items, page: 1 }

ap_personnages_details:
    path:    /details/{id}
    defaults: { _controller: APPersonnagesBundle:Details:Details }
