services:
    personnages:
        class: AP\PersonnagesBundle\Services\Personnages

    personnage:
        class: AP\PersonnagesBundle\Services\Personnage

    keys:
      class: AP\PersonnagesBundle\Services\Cles
