services:
    personnages:
        class: AP\PersonnagesBundle\Services\Personnages
        arguments:
          $publicKey: '%publicKey%'
          $privateKey: '%privateKey%'

    keys:
      class: AP\PersonnagesBundle\Services\Cles
