parameters:
    publicKey: '1577457f3589885adafd0320c0830897'
    privateKey: '5792bfaf981b65942017f8c801d117e8ed795118'

services:
    personnages:
        class: AP\PersonnagesBundle\Services\Personnages

    personnage:
        class: AP\PersonnagesBundle\Services\Personnage
